<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: welcome.proto

namespace App\Proto\GPBMetadata;

class Welcome
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7d0a0d77656c636f6d652e70726f746f224c0a0e57656c636f6d654d657373616765120c0a0474797065180120012809120f0a077061796c6f6164180220012809120c0a0475756964180320012809120d0a0571756575651804200128094216ca020550726f746fe2020b4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

